In [12]:
import pandas as pd
import numpy as np

In [28]:
data = pd.read_csv('./intermediate_datafiles/process')

In [29]:
data_ch5 = pd.read_csv('./intermediate_datafiles/chapter5_result.csv')
data.head()

,Unnamed: 0,gFx,gFy,gFz,ax,ay,az,wx,wy,wz,...,By,Bz,Azimuth,Pitch,Roll,Gain,label_bike,label_stairs,label_stand,label_walk
0,0.00,0.289130,-0.024348,0.768696,0.480435,-1.856522,0.945652,7.012609,4.826522,0.424783,...,62.313913,-30.106957,114.085217,29.715217,-25.007826,69.730000,0,0,0,1
1,0.25,0.602174,-0.008261,0.607826,0.627391,-1.024783,1.029130,4.846087,2.299130,-3.409565,...,50.556522,-13.142609,107.008696,15.066522,5.755217,77.313478,0,0,0,1
2,0.50,0.785455,-0.484545,0.295000,1.478182,-2.120455,2.682273,3.985909,-2.343636,-5.818636,...,47.705455,0.676364,76.639545,12.163182,33.172273,83.292727,0,0,0,1
3,0.75,0.673478,-0.740870,0.171304,-0.255652,-1.240435,2.845217,-0.263043,-2.132609,-2.721304,...,60.667826,3.010435,44.035217,33.481739,57.567391,84.456957,0,0,0,1
4,1.00,0.013810,-1.126190,0.056190,1.200476,-1.803333,1.207619,-3.206190,-1.785238,-2.641905,...,50.474286,2.760000,249.472381,64.675714,22.875714,85.321429,0,0,0,1

In [30]:
data["timestamp"] = 0

In [31]:
timestamp = []
for i in range(0,len(data.index)):
    timestamp.append(pd.to_datetime("6/14/2019 12:06:00") + pd.to_timedelta(data["Unnamed: 0"][i]*1000000000, unit = "ns"))
data["timestamp"] = timestamp

In [32]:
data = data.drop("Unnamed: 0", axis = 1)

In [33]:
data = data.set_index("timestamp")
data.head()

,gFx,gFy,gFz,ax,ay,az,wx,wy,wz,p,...,By,Bz,Azimuth,Pitch,Roll,Gain,label_bike,label_stairs,label_stand,label_walk
timestamp,,,,,,,,,,,,,,,,,,,,,
2019-06-14 12:06:00.000,0.289130,-0.024348,0.768696,0.480435,-1.856522,0.945652,7.012609,4.826522,0.424783,1012.118696,...,62.313913,-30.106957,114.085217,29.715217,-25.007826,69.730000,0,0,0,1
2019-06-14 12:06:00.250,0.602174,-0.008261,0.607826,0.627391,-1.024783,1.029130,4.846087,2.299130,-3.409565,1012.045217,...,50.556522,-13.142609,107.008696,15.066522,5.755217,77.313478,0,0,0,1
2019-06-14 12:06:00.500,0.785455,-0.484545,0.295000,1.478182,-2.120455,2.682273,3.985909,-2.343636,-5.818636,1011.970909,...,47.705455,0.676364,76.639545,12.163182,33.172273,83.292727,0,0,0,1
2019-06-14 12:06:00.750,0.673478,-0.740870,0.171304,-0.255652,-1.240435,2.845217,-0.263043,-2.132609,-2.721304,1011.971739,...,60.667826,3.010435,44.035217,33.481739,57.567391,84.456957,0,0,0,1
2019-06-14 12:06:01.000,0.013810,-1.126190,0.056190,1.200476,-1.803333,1.207619,-3.206190,-1.785238,-2.641905,1012.042381,...,50.474286,2.760000,249.472381,64.675714,22.875714,85.321429,0,0,0,1

In [34]:
data.to_csv("intermediate_datafiles/Data_processed_timestamps_2.csv")

In [20]:
data.shape

(3603, 21)