In [26]:
import pandas as pd
import numpy as np

In [63]:
data = pd.read_csv("data/ML4QS_testrun_2")

In [64]:
data.head()

,time,gFx,gFy,gFz,ax,ay,az,wx,wy,wz,p,Bx,By,Bz,Azimuth,Pitch,Roll,Gain,Unnamed: 18
0,13:18:00:074,0.10,0.02,1.01,0.0,0.0,0.0,0.00,0.00,0.0,0.00,0.0,0.0,0.0,0.00,0.00,0.00,-∞,NaN
1,13:18:00:078,0.10,0.02,1.01,0.0,0.0,0.0,0.00,0.00,0.0,1011.99,0.0,0.0,0.0,0.00,0.00,0.00,-∞,NaN
2,13:18:00:106,0.01,0.05,0.95,0.0,0.0,0.0,0.00,0.00,0.0,1011.99,0.0,0.0,0.0,0.00,0.00,0.00,-∞,NaN
3,13:18:00:109,0.01,0.05,0.95,0.0,0.0,0.0,0.00,0.00,0.0,1011.99,0.0,0.0,0.0,73.07,174.65,-8.34,-∞,NaN
4,13:18:00:110,0.01,0.05,0.95,0.0,0.0,0.0,1.49,1.45,19.0,1011.99,0.0,0.0,0.0,73.07,174.65,-8.34,-∞,NaN

In [72]:
df_raw = data.drop(["Unnamed: 18"], axis=1)
df_raw = df_raw[df_raw.Gain != "-∞"]
timestamps = []
for i in range(0,len(df_raw.index)):
    timestamps.append("2019:06:14 " + df_raw.time.iloc[i])
df_raw.index = timestamps    
# df_raw = df_raw.set_index("time")
# df_raw = df_raw.astype("float64")

In [73]:
df_raw.head()

,time,gFx,gFy,gFz,ax,ay,az,wx,wy,wz,p,Bx,By,Bz,Azimuth,Pitch,Roll,Gain
2019:06:14 13:18:01:045,13:18:01:045,0.12,-0.06,0.91,-0.10,-1.75,-1.13,6.93,5.08,3.37,1012.14,-68.22,60.84,-34.92,114.34,35.24,-45.96,69.73
2019:06:14 13:18:01:047,13:18:01:047,0.12,-0.06,0.91,0.28,-1.82,0.23,6.93,5.08,3.37,1012.14,-68.22,60.84,-34.92,114.34,35.24,-45.96,69.73
2019:06:14 13:18:01:049,13:18:01:049,0.12,-0.06,0.91,0.28,-1.82,0.23,6.93,5.08,3.37,1012.14,-68.22,60.84,-34.92,118.84,33.59,-31.77,69.73
2019:06:14 13:18:01:052,13:18:01:052,0.12,-0.06,0.91,0.28,-1.82,0.23,5.47,4.85,1.99,1012.14,-68.22,60.84,-34.92,118.84,33.59,-31.77,69.73
2019:06:14 13:18:01:054,13:18:01:054,-0.09,-0.05,0.65,0.28,-1.82,0.23,5.47,4.85,1.99,1012.14,-68.22,60.84,-34.92,118.84,33.59,-31.77,69.73

In [74]:
df_raw.index = pd.to_datetime(df_raw.index, format="%Y:%m:%d %H:%M:%S:%f")

In [75]:
df_raw.head()

,time,gFx,gFy,gFz,ax,ay,az,wx,wy,wz,p,Bx,By,Bz,Azimuth,Pitch,Roll,Gain
2019-06-14 13:18:01.045,13:18:01:045,0.12,-0.06,0.91,-0.10,-1.75,-1.13,6.93,5.08,3.37,1012.14,-68.22,60.84,-34.92,114.34,35.24,-45.96,69.73
2019-06-14 13:18:01.047,13:18:01:047,0.12,-0.06,0.91,0.28,-1.82,0.23,6.93,5.08,3.37,1012.14,-68.22,60.84,-34.92,114.34,35.24,-45.96,69.73
2019-06-14 13:18:01.049,13:18:01:049,0.12,-0.06,0.91,0.28,-1.82,0.23,6.93,5.08,3.37,1012.14,-68.22,60.84,-34.92,118.84,33.59,-31.77,69.73
2019-06-14 13:18:01.052,13:18:01:052,0.12,-0.06,0.91,0.28,-1.82,0.23,5.47,4.85,1.99,1012.14,-68.22,60.84,-34.92,118.84,33.59,-31.77,69.73
2019-06-14 13:18:01.054,13:18:01:054,-0.09,-0.05,0.65,0.28,-1.82,0.23,5.47,4.85,1.99,1012.14,-68.22,60.84,-34.92,118.84,33.59,-31.77,69.73

In [82]:
timestamps = []
for i in range(0, len(df_raw.index)):
    timestamps.append('%.3f' % (float(df_raw.index[i].to_datetime64().item())/1000000000))
df_raw.index = timestamps

In [83]:
df_raw.head()

,time,gFx,gFy,gFz,ax,ay,az,wx,wy,wz,p,Bx,By,Bz,Azimuth,Pitch,Roll,Gain
1560518281.045,13:18:01:045,0.12,-0.06,0.91,-0.10,-1.75,-1.13,6.93,5.08,3.37,1012.14,-68.22,60.84,-34.92,114.34,35.24,-45.96,69.73
1560518281.047,13:18:01:047,0.12,-0.06,0.91,0.28,-1.82,0.23,6.93,5.08,3.37,1012.14,-68.22,60.84,-34.92,114.34,35.24,-45.96,69.73
1560518281.049,13:18:01:049,0.12,-0.06,0.91,0.28,-1.82,0.23,6.93,5.08,3.37,1012.14,-68.22,60.84,-34.92,118.84,33.59,-31.77,69.73
1560518281.052,13:18:01:052,0.12,-0.06,0.91,0.28,-1.82,0.23,5.47,4.85,1.99,1012.14,-68.22,60.84,-34.92,118.84,33.59,-31.77,69.73
1560518281.054,13:18:01:054,-0.09,-0.05,0.65,0.28,-1.82,0.23,5.47,4.85,1.99,1012.14,-68.22,60.84,-34.92,118.84,33.59,-31.77,69.73

In [76]:
df_raw.index[0]

Timestamp('2019-06-14 13:18:01.045000')

In [81]:
'%.3f' % (float(df_raw.index[i].to_datetime64().item())/1000000000)

'1560519181.735'

In [84]:
labels = pd.read_csv("data/Interval2.csv")

IOError: File data/Interval2.csv does not exist